
nombre: Build and Deploy
donde: [push]
permisiones:
  contentos: write
jobs:
  build-and-deploy:
    concurrency: ci-${{github.ref}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        usos: actions/checkout@v3

      - name: Deploy
        usos: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: . # The folder the action should deploy.
          config: baseUrl=/